### ISSUE TITLE
Rename it to LangStream?

### ISSUE THREAD

**Issue by rogeriochaves** [rogeriochaves/langstream#4]
hey folks, I was considering the suggestion to change LiteChain name to LangStream, and subsequently change the main constructor from Chain to Stream. I think it's a big move to not be taken lightly so I wanted to hear y'alls opinion, but I think it's early enough on the project that a move like this is possible

Some pros for it:
It removes the confusion with blockchain stuff
Stream is a much more well established programming concept, and it's what the library actually do, 'chain' is a neologism in programming, getting popularized in LLMs world because of the chain-of-thought paper and langchain I feel
Make it more clear that you need to consider that everything is streamed when using the library

Some cons:
Breaking change of course
Loses the "lite" part of the name
Maybe make it less clear for people comming from LangChain to make the switch

thoughts?

**Comment by Dessix** [comment]
I vote to rename. Any association with the word "chain" is incidental, and is not present in multiple of LangChain's competitors, nor many of its own "Lang<*>" derivatives and extensions. "Lite" doesn't really describe the composability benefits of a monadic transform, even if it is technically light-weight at the implementation layer.

**Comment by odiseo0** [comment]
I also vote to rename it

**Comment by rogeriochaves** [comment]
according to comments here, on discord and some offline conversations I had, most people think this is a good idea, so thank for voting folks, the rename from LiteChain to LangStream is now done! 🎉

I've released it on [v0.1.7](https://github.com/rogeriochaves/langstream/releases/tag/v0.1.7)

to migrate it should be easy enough, change the dependency and imports from `litechain` to `langstream`, and replace all matches of `chain` to `stream` and matches of `Chain` to `Stream` in your project

**Comment by davidljung** [comment]
Is this the same as https://langstream.ai/ or different?

**Comment by nevercast** [comment]
> Is this the same as https://langstream.ai/ or different?

I do believe they are very different, this confused me as I found langstream.ai first .
