### ISSUE TITLE
Integrate OpenAI function calling

### ISSUE THREAD

**Issue by ezzcodeezzlife** [rogeriochaves/langstream#9]
Hey, love th eproject, any plan to integrate [this](https://openai.com/blog/function-calling-and-other-api-updates)

**Comment by rogeriochaves** [comment]
hey @ezzcodeezzlife, function calling is already integrated, check it out on the docs!

https://rogeriochaves.github.io/langstream/docs/llms/open_ai_functions

hope it helps, closing the issue, let me know if anything else
